import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app/app.dart';
import 'core/services/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight,
  ]);

  // Initialize Firebase on mobile/desktop only
  // Web requires proper firebase_options.dart generated by flutterfire
  if (!kIsWeb) {
    try {
      await Firebase.initializeApp();
    } catch (e, st) {
      // Log but don't rethrow
      // ignore: avoid_print
      print('Warning: Firebase.initializeApp() failed: $e\n$st');
    }
  }

  // Initialize Hive for offline storage
  await Hive.initFlutter();
  await Hive.openBox('questions_cache');
  await Hive.openBox('exams_cache');
  await Hive.openBox('user_cache');

  // Initialize SharedPreferences
  final prefs = await SharedPreferences.getInstance();

  // Initialize Notifications (mobile/desktop only)
  if (!kIsWeb) {
    try {
      await NotificationService.initialize();
    } catch (e) {
      // ignore: avoid_print
      print('Warning: NotificationService.initialize() failed: $e');
    }
  }

  // System UI overlay style (mobile only)
  if (!kIsWeb) {
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    );
  }

  runApp(
    ProviderScope(
      overrides: [sharedPreferencesProvider.overrideWithValue(prefs)],
      child: const JobProstutiApp(),
    ),
  );
}

final sharedPreferencesProvider = Provider<SharedPreferences>((ref) {
  throw UnimplementedError('SharedPreferences not initialized');
});
